{% set version = "5.1.0" %}

package:
  name: chardet
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/chardet/chardet-{{ version }}.tar.gz
  sha256: 0d62712b956bc154f85fb0a266e2a3c5913c2967e00348701b32411d6def31e5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv
  entry_points:
    - chardetect = chardet.cli.chardetect:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - chardet
  commands:
    - chardetect --help

about:
  home: https://github.com/chardet/chardet
  license: LGPL-2.1-only
  license_family: GPL
  license_file: LICENSE
  summary: Universal character encoding detector
  description: |
    chardet is a character encoding auto-detector in Python.
  doc_url: http://chardet.readthedocs.org/
  doc_source_url: https://github.com/chardet/chardet/blob/master/docs/index.rst
  dev_url: https://github.com/chardet/chardet


extra:
  recipe-maintainers:
    - dan-blanchard
    - sigmavirus24
    - nehaljwani
